export enum AppActionEnums {
	MOBILE_NAVIGATION_MENU = 'MOBILE_NAVIGATION_MENU',
	CART_CHANGE_QUANTITY='CART_CHANGE_QUANTITY',
	CART_ADD_ITEM='CART_ADD_ITEM',
	CART_REMOVE_ITEM='CART_REMOVE_ITEM',
	CART_CLEAR_ALL='CART_CLEAR_ALL'
}