- name: Build Docker image
  community.docker.docker_image:
    name: camworld_next
    state: present
    force_source: yes
    source: build
    build:
      path: "{{ dir }}"
      dockerfile: Dockerfile

- name: Restart Docker container
  community.docker.docker_container:
    name: app
    image: camworld_next
    restart: yes
    recreate: yes
    ports:
      - "5555:5555"
    env:
      NODE_ENV: "{{ NODE_ENV }}"
