import type {NextPage} from 'next'
import Head from 'next/head'
import {gql, useQuery} from '@apollo/client'
import styles from '../styles/Home.module.css'
import {useAction} from '../hook/useAction'
import {useTypedSelector} from '../hook/useTypedSelector'

export const TEST_QUERY = gql`
    query {
        getCategories {
            id, slug
        }
    }
`

const Home: NextPage = () => {
	const {toggleMenu} = useAction()
	const mobMenu = useTypedSelector(state => state.app.visibleMobileMenu)

	const {loading, error, data} = useQuery(TEST_QUERY)
	console.log(loading)
	console.log(error)
	console.log(data)

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>
			</main>
		</div>
	)
}

export default Home
