import type {NextPage} from 'next'
import Head from 'next/head'
import {gql, useQuery} from '@apollo/client'
import {useTypedSelector} from '../hook/useTypedSelector'

import {store} from "../store";
import {toggleMenu} from "../store/action-creator/global-action-creator";

export const TEST_QUERY = gql`
    query {
        getCategories {
            id, slug
        }
    }
`

const Home: NextPage = () => {
	store.dispatch(toggleMenu(true))
	const mobMenu = useTypedSelector(state => state.app.visibleMobileMenu)

	const {loading, error, data} = useQuery(TEST_QUERY)


	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>

			<main>
				<h1>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>
			</main>
		</div>
	)
}

export default Home
